# Generated by Django 4.2.16 on 2024-09-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_sensordata_current_alter_sensordata_humidity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motorcontrol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='motorcontrol',
            name='power',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='motorcontrol',
            name='speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='current',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='humidity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='temperature',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='sensordata',
            name='voltage',
            field=models.FloatField(default=0.0),
        ),
    ]
