# Generated by Django 4.2.16 on 2024-09-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_motorcontrol_id_alter_motorcontrol_power_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AverageSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature_avg', models.FloatField(default=0.0)),
                ('humidity_avg', models.FloatField(default=0.0)),
                ('current_avg', models.FloatField(default=0.0)),
                ('voltage_avg', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='RawSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperature', models.FloatField(default=0.0)),
                ('humidity', models.FloatField(default=0.0)),
                ('current', models.FloatField(default=0.0)),
                ('voltage', models.FloatField(default=0.0)),
            ],
        ),
    ]
